name: thdocs

on:
  push:
    branches: [main, thdocs]
  pull_request:
    branches: [main]

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: dtinth/thdocs/.github/workflows/publish.yml@main
    with:
      deploy: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/thdocs') }}
